### ISSUE TITLE
Global Scope breaks PermissionUserSprunje in postgres

### ISSUE THREAD

**Issue by ghost** [userfrosting/extend-user#5]
When the PermissionUserSprunje builds its underlying SQL statement, its uses a `Group By` statement.  This is incompatible with postgres, which throws the following error:

```
ERROR:  column "members.city" must appear in the GROUP BY clause or be used in an aggregate function
```

The error manifests itself on `{{site.url}}/permissions/p/4`

I am looking at ways to change the join statement to make it compatible with subsequent group by statements.

**Comment by lcharette** [comment]
I know with MySQL any column used in a GROUP BY needs to be explicitly in the `SELECT` list. Could it be the same with postgres?

**Comment by ghost** [comment]
Yes that is the case but then i think this extended user sprinkle needs to overwrite the permissions sprunje also to not break core functionality.
