### ISSUE TITLE
 'UserFrosting\System\Bakery\Migration' not found

### ISSUE THREAD

**Issue by bwilhelm** [userfrosting/extend-user#7]
I followed the install instructions, ran 'composer update' and then 'php bakery bake' and received the following:

`UserFrosting's Migrator
=======================

<strong>Fatal error</strong>: Uncaught Error: Class 'UserFrosting\System\Bakery\Migration' not found in C:\Users\bwilh\Documents\Development_L
ocal\KOWOP_Manager\app\sprinkles\extend-user\src\Database\Migrations\v400\MembersTable.php:8
Stack trace:
#0 C:\Users\bwilh\Documents\Development_Local\KOWOP_Manager\app\vendor\composer\ClassLoader.php(478): include()
#1 C:\Users\bwilh\Documents\Development_Local\KOWOP_Manager\app\vendor\composer\ClassLoader.php(346): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 [internal function]: spl_autoload_call()
#4 C:\Users\bwilh\Documents\Development_Local\KOWOP_Manager\app\sprinkles\core\src\Database\Migrator\MigrationDependencyAnalyser.php(207): cla
ss_exists()
#5 C:\Users\bwilh\Documents\Development_Local\KOWOP_Manager\app\sprinkles\core\src\Database\Migrator\MigrationDependencyAnalyser.php(115): Use
rFrosting\Sprinkle\Core\Database\Migrator\MigrationDependencyAnalyser->getMigrationDependencies()
#6 C:\Users\bwilh\Documents\Development_Local\KOWOP_Man in <strong>C:\Users\bwilh\Documents\Development_Local\KOWOP_Manager\app\sprinkles\exte
nd-user\src\Database\Migrations\v400\MembersTable.php</strong> on line <strong>8</strong>`

That seems like a core component that is 'not found'. I realize this Sprinkle is 4 years old, but if it doesn't work, you might want to archive it.

**Comment by lcharette** [comment]
Note, this sprinkle needs to be updated for UF 4.5. The class needs to be updated to `UserFrosting\Sprinkle\Core\Database\Migration`. The old one was removed in UF4.5 I think.
